from __future__ import annotations

THEMES: dict[str, dict] = {
    "octo_dark_blue": {
        "id": "octo_dark_blue",
        "name": "Octo Dark Blue",
        "colors": {
            "bg": "#343941",
            "bg2": "#252932",
            "card": "#292b31",
            "card_soft": "#30333b",
            "border": "rgba(255,255,255,0.09)",
            "text": "#f4f4f5",
            "muted": "#b8bdc8",
            "primary": "#49669c",
            "primary_hover": "#5878b5",
            "success": "#22c55e",
            "warning": "#eab308",
            "danger": "#ef4444",
            "shadow": "rgba(0,0,0,0.35)",
        },
        "fonts": {
            "base": "Terminal Modern",
            "heading": "Terminal Modern",
            "number": "Terminal Modern",
            "button": "Terminal Modern",
        },
        "effects": {
            "glass": False,
            "fade_in": True,
            "scanlines": False,
            "radius": "14px",
            "shadow_strength": "medium",
        },
    },
    "amber_terminal": {
        "id": "amber_terminal",
        "name": "Amber Terminal",
        "colors": {
            "bg": "#12100b",
            "bg2": "#20180e",
            "card": "rgba(29, 22, 14, 0.92)",
            "card_soft": "rgba(45, 33, 18, 0.9)",
            "border": "rgba(255,180,72,0.18)",
            "text": "#ffe7b3",
            "muted": "#c9a96f",
            "primary": "#b46b1d",
            "primary_hover": "#d18228",
            "success": "#55e17a",
            "warning": "#f6be3b",
            "danger": "#ff5a4d",
            "shadow": "rgba(255,154,46,0.10)",
        },
        "fonts": {
            "base": "Terminal Classic",
            "heading": "Sci-Fi Console",
            "number": "Terminal Modern",
            "button": "Sci-Fi Console",
        },
        "effects": {
            "glass": True,
            "fade_in": True,
            "scanlines": True,
            "radius": "12px",
            "shadow_strength": "glow",
        },
    },
    "mainsail_dark": {
        "id": "mainsail_dark",
        "name": "Mainsail-ish Dark",
        "colors": {
            "bg": "#1f2937",
            "bg2": "#111827",
            "card": "#263244",
            "card_soft": "#2e3b4f",
            "border": "rgba(255,255,255,0.08)",
            "text": "#f9fafb",
            "muted": "#cbd5e1",
            "primary": "#2563eb",
            "primary_hover": "#3b82f6",
            "success": "#10b981",
            "warning": "#f59e0b",
            "danger": "#ef4444",
            "shadow": "rgba(0,0,0,0.35)",
        },
        "fonts": {
            "base": "System Sans",
            "heading": "System Sans",
            "number": "Terminal Modern",
            "button": "System Sans",
        },
        "effects": {
            "glass": False,
            "fade_in": True,
            "scanlines": False,
            "radius": "16px",
            "shadow_strength": "medium",
        },
    },
    "carbon_glass": {
        "id": "carbon_glass",
        "name": "Carbon Glass",
        "colors": {
            "bg": "#0f172a",
            "bg2": "#1e293b",
            "card": "rgba(15,23,42,0.72)",
            "card_soft": "rgba(30,41,59,0.76)",
            "border": "rgba(148,163,184,0.18)",
            "text": "#f8fafc",
            "muted": "#cbd5e1",
            "primary": "#475569",
            "primary_hover": "#64748b",
            "success": "#22c55e",
            "warning": "#eab308",
            "danger": "#ef4444",
            "shadow": "rgba(2,6,23,0.55)",
        },
        "fonts": {
            "base": "Industrial Mono",
            "heading": "Industrial Mono",
            "number": "Terminal Modern",
            "button": "Industrial Mono",
        },
        "effects": {
            "glass": True,
            "fade_in": True,
            "scanlines": False,
            "radius": "18px",
            "shadow_strength": "heavy",
        },
    },

    "toxic_green": {
        "id": "toxic_green",
        "name": "Toxic Green Lab",
        "colors": {
            "bg": "#041007",
            "bg2": "#061b0c",
            "card": "rgba(5, 21, 10, 0.9)",
            "card_soft": "rgba(9, 34, 15, 0.92)",
            "border": "rgba(87,255,117,0.2)",
            "text": "#e8ffe8",
            "muted": "#9fd3a5",
            "primary": "#20c45a",
            "primary_hover": "#42f57b",
            "success": "#5cff89",
            "warning": "#e6f75c",
            "danger": "#ff4971",
            "shadow": "rgba(34,255,93,0.12)",
        },
        "fonts": {
            "base": "Terminal Classic",
            "heading": "Sci-Fi Console",
            "number": "Terminal Modern",
            "button": "Sci-Fi Console",
        },
        "effects": {
            "glass": True,
            "fade_in": True,
            "scanlines": True,
            "radius": "12px",
            "shadow_strength": "glow",
        },
    },
    "blood_terminal": {
        "id": "blood_terminal",
        "name": "Blood Red Terminal",
        "colors": {
            "bg": "#100405",
            "bg2": "#24070a",
            "card": "rgba(30, 7, 9, 0.9)",
            "card_soft": "rgba(50, 12, 15, 0.92)",
            "border": "rgba(255,86,86,0.2)",
            "text": "#ffe8e8",
            "muted": "#d69b9b",
            "primary": "#b71f2e",
            "primary_hover": "#e33b4b",
            "success": "#65e08b",
            "warning": "#f5b944",
            "danger": "#ff4d4d",
            "shadow": "rgba(255,40,40,0.14)",
        },
        "fonts": {
            "base": "Industrial Mono",
            "heading": "Sci-Fi Console",
            "number": "Terminal Modern",
            "button": "Industrial Mono",
        },
        "effects": {
            "glass": True,
            "fade_in": True,
            "scanlines": True,
            "radius": "13px",
            "shadow_strength": "glow",
        },
    },
    "elegoo_dark": {
        "id": "elegoo_dark",
        "name": "Elegoo Dark",
        "colors": {
            "bg": "#171718",
            "bg2": "#202123",
            "card": "#242526",
            "card_soft": "#303133",
            "border": "rgba(255,255,255,0.1)",
            "text": "#f7f7f8",
            "muted": "#b8b8bd",
            "primary": "#ff7a1a",
            "primary_hover": "#ff9440",
            "success": "#38d878",
            "warning": "#ffcc4d",
            "danger": "#ff5c5c",
            "shadow": "rgba(0,0,0,0.42)",
        },
        "fonts": {
            "base": "System Sans",
            "heading": "System Sans",
            "number": "Terminal Modern",
            "button": "System Sans",
        },
        "effects": {
            "glass": False,
            "fade_in": True,
            "scanlines": False,
            "radius": "12px",
            "shadow_strength": "medium",
        },
    },
    "klipper_blue": {
        "id": "klipper_blue",
        "name": "Klipper Blue",
        "colors": {
            "bg": "#07111f",
            "bg2": "#0d1b2e",
            "card": "rgba(13, 27, 46, 0.92)",
            "card_soft": "rgba(20, 38, 62, 0.94)",
            "border": "rgba(106,164,255,0.18)",
            "text": "#eaf3ff",
            "muted": "#a8bed8",
            "primary": "#2f81f7",
            "primary_hover": "#58a6ff",
            "success": "#3ddc84",
            "warning": "#f5c451",
            "danger": "#ff5f72",
            "shadow": "rgba(0,38,100,0.45)",
        },
        "fonts": {
            "base": "System Sans",
            "heading": "System Sans",
            "number": "Terminal Modern",
            "button": "System Sans",
        },
        "effects": {
            "glass": True,
            "fade_in": True,
            "scanlines": False,
            "radius": "16px",
            "shadow_strength": "medium",
        },
    },
    "oled_mono": {
        "id": "oled_mono",
        "name": "OLED Mono",
        "colors": {
            "bg": "#000000",
            "bg2": "#050505",
            "card": "#080808",
            "card_soft": "#121212",
            "border": "rgba(255,255,255,0.16)",
            "text": "#f7f7f7",
            "muted": "#a8a8a8",
            "primary": "#4b5563",
            "primary_hover": "#6b7280",
            "success": "#ffffff",
            "warning": "#d8d8d8",
            "danger": "#ff7474",
            "shadow": "rgba(0,0,0,0.95)",
        },
        "fonts": {
            "base": "Terminal Modern",
            "heading": "Terminal Modern",
            "number": "Terminal Modern",
            "button": "Terminal Modern",
        },
        "effects": {
            "glass": False,
            "fade_in": False,
            "scanlines": False,
            "radius": "8px",
            "shadow_strength": "none",
        },
    },
    "cyberpunk_magenta": {
        "id": "cyberpunk_magenta",
        "name": "Cyberpunk Magenta",
        "colors": {
            "bg": "#0d0615",
            "bg2": "#160b2c",
            "card": "rgba(23, 10, 43, 0.9)",
            "card_soft": "rgba(38, 16, 66, 0.92)",
            "border": "rgba(255,75,216,0.18)",
            "text": "#fff0ff",
            "muted": "#d4a8df",
            "primary": "#d946ef",
            "primary_hover": "#f472b6",
            "success": "#34f5c5",
            "warning": "#facc15",
            "danger": "#ff4f8b",
            "shadow": "rgba(217,70,239,0.16)",
        },
        "fonts": {
            "base": "Sci-Fi Console",
            "heading": "Sci-Fi Console",
            "number": "Terminal Modern",
            "button": "Sci-Fi Console",
        },
        "effects": {
            "glass": True,
            "fade_in": True,
            "scanlines": True,
            "radius": "18px",
            "shadow_strength": "glow",
        },
    },
    "retro_crt_blue": {
        "id": "retro_crt_blue",
        "name": "Retro CRT Blue-Gray",
        "colors": {
            "bg": "#05080d",
            "bg2": "#101720",
            "card": "rgba(12, 19, 28, 0.92)",
            "card_soft": "rgba(22, 31, 44, 0.94)",
            "border": "rgba(133, 163, 196, 0.18)",
            "text": "#d7e4ee",
            "muted": "#93a8bb",
            "primary": "#5f7f9a",
            "primary_hover": "#7f9cb5",
            "success": "#7fdcaa",
            "warning": "#d5be73",
            "danger": "#e68181",
            "shadow": "rgba(71, 109, 149, 0.20)",
        },
        "fonts": {
            "base": "Retro CRT",
            "heading": "Retro CRT",
            "number": "Retro CRT",
            "button": "Retro CRT",
        },
        "effects": {
            "glass": True,
            "fade_in": True,
            "scanlines": True,
            "radius": "10px",
            "shadow_strength": "glow",
        },
    },
    "green_phosphor_crt": {
        "id": "green_phosphor_crt",
        "name": "Green Phosphor CRT",
        "colors": {
            "bg": "#020403",
            "bg2": "#07100a",
            "card": "rgba(4, 12, 7, 0.93)",
            "card_soft": "rgba(8, 22, 12, 0.94)",
            "border": "rgba(103, 255, 156, 0.20)",
            "text": "#bcffd0",
            "muted": "#76b389",
            "primary": "#33d16f",
            "primary_hover": "#5af592",
            "success": "#7dffb0",
            "warning": "#d7c76e",
            "danger": "#ff6f6f",
            "shadow": "rgba(67, 255, 134, 0.18)",
        },
        "fonts": {
            "base": "Retro CRT",
            "heading": "Retro CRT",
            "number": "Retro CRT",
            "button": "Retro CRT",
        },
        "effects": {
            "glass": True,
            "fade_in": True,
            "scanlines": True,
            "radius": "10px",
            "shadow_strength": "glow",
        },
    },
    "high_contrast": {
        "id": "high_contrast",
        "name": "High Contrast",
        "colors": {
            "bg": "#000000",
            "bg2": "#111111",
            "card": "#161616",
            "card_soft": "#202020",
            "border": "rgba(255,255,255,0.22)",
            "text": "#ffffff",
            "muted": "#e5e5e5",
            "primary": "#1d4ed8",
            "primary_hover": "#2563eb",
            "success": "#22c55e",
            "warning": "#facc15",
            "danger": "#f87171",
            "shadow": "rgba(0,0,0,0.8)",
        },
        "fonts": {
            "base": "System Sans",
            "heading": "System Sans",
            "number": "Terminal Modern",
            "button": "System Sans",
        },
        "effects": {
            "glass": False,
            "fade_in": False,
            "scanlines": False,
            "radius": "10px",
            "shadow_strength": "none",
        },
    },
}

FONT_STACKS: dict[str, str] = {
    "Terminal Modern": '"JetBrains Mono", "Fira Code", "Cascadia Mono", "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
    "Terminal Classic": '"Share Tech Mono", "VT323", "Courier New", Consolas, "Liberation Mono", monospace',
    "Industrial Mono": '"IBM Plex Mono", "Roboto Mono", "Cascadia Mono", Consolas, "Liberation Mono", monospace',
    "Sci-Fi Console": '"Oxanium", "Share Tech Mono", "JetBrains Mono", Consolas, monospace',
    "Retro CRT": '"VT323", "Courier New", monospace',
    "System Sans": 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
}


def get_theme(theme_id: str | None) -> dict:
    return THEMES.get(theme_id or "octo_dark_blue", THEMES["octo_dark_blue"])


def theme_css_vars(theme_id: str | None, appearance: dict | None = None) -> str:
    theme = get_theme(theme_id)
    appearance = appearance or {}
    colors = theme["colors"]
    fonts = dict(theme.get("fonts", {}))
    overrides = appearance.get("fonts", {}) if isinstance(appearance.get("fonts", {}), dict) else {}
    fonts.update({k: v for k, v in overrides.items() if v})

    def stack(name: str, fallback: str = "Terminal Modern") -> str:
        return FONT_STACKS.get(fonts.get(name, fallback), FONT_STACKS[fallback])

    return "\n".join(
        [
            f"--cc2-{key.replace('_', '-')}: {value};" for key, value in colors.items()
        ]
        + [
            f"--cc2-radius: {theme.get('effects', {}).get('radius', '14px')};",
            f"--font-base: {stack('base')};",
            f"--font-heading: {stack('heading')};",
            f"--font-number: {stack('number')};",
            f"--font-button: {stack('button')};",
        ]
    )
